language: go
go:
- "1.11.x"
matrix:
    fast_finish: true
sudo: false
before_install:
- go get github.com/golang/lint/golint
- go get golang.org/x/tools/cmd/stringer
- go get -t -v $(go list ./... | grep -v '/vendor/')
before_script:
- golint ./...
- go vet ./...
- go generate ./...
- gofmt -w .
- test -z `git diff`
script:
- go test ./...
