language: go
go:
- "1.11.x"
matrix:
    fast_finish: true
sudo: false
before_install:
- curl -sLOf https://raw.githubusercontent.com/MStoykov/fmtpolice/master/coverage
- go get github.com/axw/gocov/gocov github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- go get github.com/golang/lint/golint
- go get -t -v $(go list ./... | grep -v '/vendor/')
before_script:
- golint ./...
- go vet ./...
- go generate ./..
- test -z `git diff`
script:
- bash coverage -v
after_script:
- "$HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci"
